# Site settings
title: Drumil Bakhai
email: dkb300@nyu.edu
url: https://drumilbakhai.github.io
description: "Junior DevOps Engineer that will help organization to get Automated Delivery as quick as possiblefeed.xml site description."
skills: "Software / Data Engineering | Junior DevOps Engineer"
meta_author: Bakhai Drumil

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Drumil Bakhai
  location: Location
  social: Web Presence
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
  - title: linkedin
    url: https://www.linkedin.com/in/drumil-bakhai-3a0b74125/
  
  
  - title: github
    url: http://github.com/drumilbakhai

# Postal address (add as many lines as necessary)
address:
  - line: 367 86th Street,
  - line: Brooklyn, NY 11209

# Credits content
credits: 'Thank you Github pages and Dr. Jekyll'

# Build settings
markdown: kramdown
permalink: pretty
